services:
  chv-bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/bot/logs
      - ./configs:/usr/src/bot/configs
      - ./modules:/usr/src/bot/modules
    deploy:
      restart_policy:
        condition: unless-stopped
        delay: 10s
        window: 120s
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - OWNER_ID=${OWNER_ID}
