services:
  chv-bot:
    build: .
    volumes:
      - ./logs:/usr/src/bot/logs
      - ./configs:/usr/src/bot/configs
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - OWNER_ID=${OWNER_ID}
    networks:
      - multi-domain

networks:
  multi-domain:
    external: true
    name: multi-domain
