services:
  chv-bot:
    container_name: codeforce-thhv-bot
    build: .
    volumes:
      - ./logs:/usr/src/bot/logs
      - ./configs:/usr/src/bot/configs
    environments:
      - TOKEN=your_token
      - CLIENT_ID=your_id
      - OWNER_ID=your_id
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s