services:
  chv-bot:
    container_name: codeforce-thhv-bot
    build: .
    volumes:
      - ./logs:/usr/src/bot/logs
      - ./configs:/usr/src/bot/configs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s